python edit.py \
    --source_prompt 'A photo of white boy at 10 years old.' \
    --target_prompt 'A photo of white male at 70 years old, smooth clear skin with even tone, faint fine lines softened by care, forehead nearly uncreased, cheeks subtly full with balanced contour, bright eyes with minimal under-eye puffiness, lips well-shaped and hydrated, jawline firm and well-defined, complexion luminous with healthy glow, overall visage reflecting meticulous grooming, cosmetic upkeep, and slower visible aging, captured with detailed realistic photographic clarity.' \
    --target_age 70 \
    --input_age 10 \
    --guidance 2 \
    --source_img_dir /playpen-nas-ssd/gongbang/missing_kid/lost_kid.jpg \
    --num_steps 15 \
    --inject 3 \
    --name 'flux-dev' \
    --offload \
    --output_dir /playpen-nas-ssd/gongbang/missing_kid_res \
    --direction_path /playpen-nas-ssd3/gongbang/general_aging_features/editing_direction_general_kv/